### ISSUE TITLE
Feature for logging to syslog?

### ISSUE THREAD

**Issue by jwilm** [sfackler/rust-log-panics#1]
Hey @sfackler,

I'm thinking about adding syslog panic logging to my project, and I was wondering if you'd be interested in a patch that adds it to this crate behind a feature gate. What do you think?

**Comment by sfackler** [comment]
This just uses the `log` crate, so it seems like the way to do that would be to have a logger implementation that hits syslog. I think there may be some existing crates like that, and there's an outstanding issue on log4rs to add a syslog appender that's just blocked on an implementation.

**Comment by jwilm** [comment]
Interesting! So one would configure an appender for the `log_panics` module which directs to syslog while ignoring everything else. That sounds way better.
