### ISSUE TITLE
Change log target from `log_panics` to `panic`

### ISSUE THREAD

**Issue by Thomasdezeeuw** [sfackler/rust-log-panics#2]
Currently when logging it uses the default target, which is the module name `log_panics`. But in my opinion it would be nicer to change this to `panic`, since the panic itself really has nothing to do with the module.

```
2017-08-04T12:32:58.203374+00:00 [ERROR] log_panics: thread 'tests::log_output' panicked at 'oops'
// vs
2017-08-04T12:32:58.203374+00:00 [ERROR] panic: thread 'tests::log_output' panicked at 'oops'
```

Would a change like that be acceptable?

**Comment by sfackler** [comment]
Sure, that seems like a fine thing to do.

**Comment by Thomasdezeeuw** [comment]
Thanks, any change for a minor update to include the change on crates.io?

**Comment by sfackler** [comment]
Done

**Comment by Thomasdezeeuw** [comment]
Thanks.
